internlm2_5-7b-hf:
    demo_gsm8k: 42.19
    race-middle: 91.78
    race-high: 90.02

internlm2-1.8b-hf:
    demo_gsm8k: 71.66
    race-middle: 91.78
    race-high: 66.38

internlm2_5-7b-chat-lmdeploy:
    demo_gsm8k: 90.54
    race-middle: 92.76
    race-high: 85.94

internlm2-chat-1.8b-lmdeploy:
    demo_gsm8k: 28.12
    race-middle: 81.34
    race-high: 73.96
