internlm2_5-7b-chat-hf_fullbench:
    race-high: 93.75
    ARC-c: 87.5
    BoolQ: 81.25
    drop: 81.25
    GPQA_diamond: 25
    math: 75
    wikibench-wiki-single_choice_cncircular: 50
    sanitized_mbpp: 68.75
    ds1000: 16.96
    gsm8k: 56.25
    triviaqa_wiki_1shot: 50
    nq_open_1shot: 25
    hellaswag: 87.5
    TheoremQA: 18.75
    college_knowledge: 87.5
    bbh-temporal_sequences: 100
    bbh-multistep_arithmetic_two: 68.75
    mmlu-other: 72.6
    cmmlu-china-specific: 76.25
    mmlu_pro_math: 25
    ds1000_Pandas: 12.5
    ds1000_Numpy: 0
    ds1000_Tensorflow: 12.5
    ds1000_Scipy: 18.75
    ds1000_Sklearn: 18.75
    ds1000_Pytorch: 12.5
    ds1000_Matplotlib: 43.75


internlm2_5-7b-chat-turbomind_fullbench:
    race-high: 93.75
    ARC-c: 87.5
    BoolQ: 68.75
    drop: 75
    GPQA_diamond: 25
    math: 75
    wikibench-wiki-single_choice_cncircular: 25
    sanitized_mbpp: 68.75
    ds1000: 13.39
    gsm8k: 68.75
    triviaqa_wiki_1shot: 50
    nq_open_1shot: 25
    hellaswag: 81.25
    TheoremQA: 6.25
    college_knowledge: 87.5
    bbh-temporal_sequences: 100
    bbh-multistep_arithmetic_two: 68.75
    mmlu-other: 74.04
    cmmlu-china-specific: 76.25
    mmlu_pro_math: 25
    ds1000_Pandas: 0
    ds1000_Numpy: 0
    ds1000_Tensorflow: 12.5
    ds1000_Scipy: 18.75
    ds1000_Sklearn: 18.75
    ds1000_Pytorch: 6.25
    ds1000_Matplotlib: 37.5
