baichuan2-7b-chat-hf:
    gsm8k: 18.75
    race-middle: 84.38
    race-high: 78.12

glm-4-9b-chat-hf:
    gsm8k: 68.75
    race-middle: 90.62
    race-high: 90.62

glm-4-9b-chat-turbomind:
    gsm8k: 71.88
    race-middle: 90.62
    race-high: 90.62

glm-4-9b-chat-vllm:
    gsm8k: 65.62
    race-middle: 90.62
    race-high: 90.62

deepseek-7b-chat-hf:
    gsm8k: 46.88
    race-middle: 78.12
    race-high: 81.25

deepseek-moe-16b-chat-hf:
    gsm8k: 50
    race-middle: 62.5
    race-high: 68.75

deepseek-7b-chat-vllm:
    gsm8k: 43.75
    race-middle: 78.12
    race-high: 75

gemma2-2b-it-hf:
    gsm8k: 50
    race-middle: 81.25
    race-high: 71.88

gemma2-9b-it-hf:
    gsm8k: 71.88
    race-middle: 87.5
    race-high: 84.38

gemma-2b-it-hf:
    gsm8k: 3.12
    race-middle: 65.62
    race-high: 40.62

gemma-7b-it-hf:
    gsm8k: 40.62
    race-middle: 71.88
    race-high: 68.75

gemma-2-9b-it-turbomind:
    gsm8k: 68.75
    race-middle: 87.5
    race-high: 84.38

gemma-7b-it-vllm:
    gsm8k: 28.12
    race-middle: 75
    race-high: 68.75

internlm2_5-7b-chat-hf:
    gsm8k: 84.38
    race-middle: 87.5
    race-high: 90.62

internlm2_5-7b-chat-turbomind:
    gsm8k: 84.38
    race-middle: 87.5
    race-high: 90.62

internlm2-chat-1.8b-turbomind:
    gsm8k: 25
    race-middle: 93.75
    race-high: 84.38

internlm2-chat-1.8b-sft-turbomind:
    gsm8k: 31.25
    race-middle: 93.75
    race-high: 84.38

internlm2-chat-7b-lmdeploy:
    gsm8k: 62.5
    race-middle: 90.62
    race-high: 87.5

internlm2-chat-7b-sft-turbomind:
    gsm8k: 53.12
    race-middle: 90.62
    race-high: 90.62

internlm2-chat-7b-vllm:
    gsm8k: 43.75
    race-middle: 93.75
    race-high: 87.5

llama-3_1-8b-instruct-hf:
    gsm8k: 84.38
    race-middle: 84.38
    race-high: 90.62

llama-3_2-3b-instruct-hf:
    gsm8k: 65.62
    race-middle: 84.38
    race-high: 81.25

llama-3-8b-instruct-hf:
    gsm8k: 68.75
    race-middle: 87.5
    race-high: 87.5

llama-3_1-8b-instruct-turbomind:
    gsm8k: 81.25
    race-middle: 84.38
    race-high: 90.62

llama-3_2-3b-instruct-turbomind:
    gsm8k: 68.75
    race-middle: 84.38
    race-high: 81.25

llama-3-8b-instruct-turbomind:
    gsm8k: 68.75
    race-middle: 87.5
    race-high: 87.5

mistral-7b-instruct-v0.2-hf:
    gsm8k: 40.62
    race-middle: 81.25
    race-high: 75

mistral-7b-instruct-v0.3-hf:
    gsm8k: 40.62
    race-middle: 78.12
    race-high: 75

mistral-nemo-instruct-2407-hf:
    gsm8k: 75
    race-middle: 84.38
    race-high: 81.25

mistral-nemo-instruct-2407-turbomind:
    gsm8k: 75
    race-middle: 84.38
    race-high: 81.25

mistral-7b-instruct-v0.1-vllm:
    gsm8k: 37.5
    race-middle: 78.12
    race-high: 71.88

mistral-7b-instruct-v0.2-vllm:
    gsm8k: 43.75
    race-middle: 78.12
    race-high: 75

MiniCPM3-4B-hf:
    gsm8k: 43.75
    race-middle: 78.12
    race-high: 75

minicpm-2b-dpo-fp32-hf:
    gsm8k: 56.25
    race-middle: 65.62
    race-high: 56.25

minicpm-2b-sft-bf16-hf:
    gsm8k: 46.88
    race-middle: 78.12
    race-high: 65.62

minicpm-2b-sft-fp32-hf:
    gsm8k: 46.88
    race-middle: 78.12
    race-high: 65.62

phi-3-mini-4k-instruct-hf:
    gsm8k: 56.25
    race-middle: 87.5
    race-high: 78.12

qwen1.5-0.5b-chat-hf:
    gsm8k: 0
    race-middle: 59.38
    race-high: 53.12

qwen2-1.5b-instruct-hf:
    gsm8k: 62.5
    race-middle: 81.25
    race-high: 84.38

qwen2-7b-instruct-hf:
    gsm8k: 68.75
    race-middle: 87.5
    race-high: 90.62

qwen2-1.5b-instruct-turbomind:
    gsm8k: 56.25
    race-middle: 81.25
    race-high: 84.38

qwen2-7b-instruct-turbomind:
    gsm8k: 78.12
    race-middle: 87.5
    race-high: 87.5

qwen1.5-0.5b-chat-vllm:
    gsm8k: 3.12
    race-middle: 59.38
    race-high: 53.12

yi-1.5-6b-chat-hf:
    gsm8k: 65.62
    race-middle: 93.75
    race-high: 84.38

yi-1.5-9b-chat-hf:
    gsm8k: 75
    race-middle: 90.62
    race-high: 93.75

deepseek-v2-lite-chat-hf:
    gsm8k: 43.75
    race-middle: 87.5
    race-high: 71.88

internlm2_5-20b-chat-hf:
    gsm8k: 84.38
    race-middle: 93.75
    race-high: 87.5

internlm2_5-20b-chat-turbomind:
    gsm8k: 87.5
    race-middle: 93.75
    race-high: 87.5

mistral-small-instruct-2409-hf:
    gsm8k: 81.25
    race-middle: 87.5
    race-high: 90.62

mistral-small-instruct-2409-turbomind:
    gsm8k: 81.25
    race-middle: 87.5
    race-high: 87.5

qwen2.5-14b-instruct-hf:
    gsm8k: 71.88
    race-middle: 93.75
    race-high: 93.75

qwen2.5-14b-instruct-turbomind:
    gsm8k: 75
    race-middle: 90.62
    race-high: 93.75

deepseek-v2-lite-hf:
    gsm8k: 37
    race-middle: 56
    race-high: 62



deepseek-7b-base-turbomind:
    gsm8k: 21
    race-middle: 42
    race-high: 42

deepseek-moe-16b-base-vllm:
    gsm8k: 22
    race-middle: 35
    race-high: 20

deepseek-moe-16b-base-hf:
    gsm8k: 25
    race-middle: 35
    race-high: 23

gemma-2b-hf:
    gsm8k: 19
    race-middle: 33
    race-high: 26

gemma-7b-hf:
    gsm8k: 65
    race-middle: 59
    race-high: 66

gemma2-2b-hf:
    gsm8k: 33
    race-middle: 56
    race-high: 58

gemma2-9b-hf:
    gsm8k: 70
    race-middle: 82
    race-high: 84

internlm2_5-7b-hf:
    gsm8k: 47
    race-middle: 92
    race-high: 91

internlm2-7b-hf:
    gsm8k: 65
    race-middle: 77
    race-high: 72

internlm2-base-7b-hf:
    gsm8k: 5
    race-middle: 71
    race-high: 74

internlm2_5-7b-turbomind:
    gsm8k: 73
    race-middle: 90
    race-high: 91

internlm2-1.8b-turbomind:
    gsm8k: 25
    race-middle: 75
    race-high: 72

internlm2-7b-turbomind:
    gsm8k: 67
    race-middle: 78
    race-high: 76

internlm2-base-7b-turbomind:
    gsm8k: 39
    race-middle: 75
    race-high: 81

llama-2-7b-hf:
    gsm8k: 17
    race-middle: 32
    race-high: 38

llama-3-8b-hf:
    gsm8k: 48
    race-middle: 64
    race-high: 70

llama-3.1-8b-turbomind:
    gsm8k: 57
    race-middle: 67
    race-high: 75

llama-3-8b-turbomind:
    gsm8k: 52
    race-middle: 63
    race-high: 70

mistral-7b-v0.2-hf:
    gsm8k: 43
    race-middle: 42
    race-high: 60

mistral-7b-v0.3-hf:
    gsm8k: 43
    race-middle: 42
    race-high: 60

mistral-7b-v0.2-vllm:
    gsm8k: 45
    race-middle: 42
    race-high: 58

qwen1.5-moe-a2.7b-hf:
    gsm8k: 64
    race-middle: 78
    race-high: 90

qwen2-1.5b-hf:
    gsm8k: 58
    race-middle: 65
    race-high: 78

qwen2-0.5b-hf:
    gsm8k: 35
    race-middle: 52
    race-high: 48

qwen2-7b-hf:
    gsm8k: 82
    race-middle: 88
    race-high: 89

qwen2-1.5b-turbomind:
    gsm8k: 57
    race-middle: 64
    race-high: 78

qwen2-7b-turbomind:
    gsm8k: 83
    race-middle: 88
    race-high: 88

qwen1.5-0.5b-vllm:
    gsm8k: 12
    race-middle: 54
    race-high: 59

yi-1.5-6b-hf:
    gsm8k: 59
    race-middle: 81
    race-high: 89

yi-1.5-9b-hf:
    gsm8k: 77
    race-middle: 90
    race-high: 90
