name: pr_stage_test

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'README_zh-CN.md'
      - 'docs/**'
      - 'configs/**'
      - 'tools/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_functions:
    runs-on: self-hosted
    timeout-minutes: 4320 # 72hours
    strategy:
      matrix:
        python-version: ['3.10']
        include:
          - torch: 2.0.0
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install PyTorch
        run: pip install torch==${{matrix.torch}}+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
      - name: Install system dependencies
        run: |
          sudo sed -i '$ a deb http://th.archive.ubuntu.com/ubuntu jammy main' /etc/apt/sources.list
          sudo apt-get update && sudo apt-get install -y libc6 libffi-dev libncursesw6 wget unzip
      - name: Upgrade pip
        run: python -m pip install pip --upgrade
      - name: Install opencompass dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Build and install
        run: python -m pip install -e .
      - name: Prepare dataset
        run: |
          wget https://github.com/open-compass/opencompass/releases/download/0.1.8.rc1/OpenCompassData-core-20231110.zip
          unzip OpenCompassData-core-20231110.zip
      - name: Dry run test
        run: |
          python run.py --models hf_opt_125m --datasets siqa_gen winograd_ppl --dry-run
      - name: run testcase
        run: |
          python run.py --models hf_opt_125m --datasets siqa_gen winograd_ppl --dry-run
  
